# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cc635d0dc3e039d26d369a256443ab9071244ad8c3d916232e1b42683a0d06115c6a7b1d5a6f99ff96243897c84e0b9259597cf9ccbb2f40f298994e224f529

test:
  secret_key_base: c9cda3692c1c5b939c0f35e3022a08106e25d595ba67f380f92ac73aa94fee80f7b6ca3e335f2fc841841538453033595be0d130306b14e2b8743938b5bfcff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
